version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    volumes:
      - ./postgres-database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  mongodb:
    image: mongo:latest
    container_name: mongo-container
    volumes:
      - ./mongo-database:/data/db
    ports:
      - "27017:27017"
